# Generated by Django 4.0.6 on 2022-07-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorias',
            name='nome',
            field=models.CharField(help_text='Nome da Auditoria', max_length=100),
        ),
    ]
