# Generated by Django 4.0.6 on 2022-07-29 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojas', '0001_initial'),
        ('auditorias', '0002_alter_auditorias_nome'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='auditoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auditorias.auditorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='lojas',
            field=models.ManyToManyField(to='lojas.loja'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
